### ISSUE TITLE
Can you share the 'latest_net_G_A.pth'?

### ISSUE THREAD

**Issue by vincentgc** [Sky24H/image2ink#1]
The performance of your method looks very good so I want to reproduce the result. But the 'latest_net_G_A.pth' is not in ./checkpoint. Can you share it? Much thanks to you!

**Comment by sky24h** [comment]
> The performance of your method looks very good so I want to reproduce the result. But the 'latest_net_G_A.pth' is not in ./checkpoint. Can you share it? Much thanks to you!

Sorry for late reply, I already uploaded G models instead of D, please check.
