### ISSUE TITLE
Does not support python3

### ISSUE THREAD

**Issue by ghost** [Sky24H/image2ink#2]
![QQ截图20191214215623](https://user-images.githubusercontent.com/14195738/70849660-a50d0400-1ebc-11ea-912c-4b45b2e0d8dc.png)

**Comment by sky24h** [comment]
Yes, I think I've already write it on README that only python2.7 is supported, I will make it supports python3 later, sorry for the inconvenience.

**Comment by sky24h** [comment]
I'm sorry for being impossibly late, I just updated this repo to be compatible with Python 3.9 and free of bugs.
