### ISSUE TITLE
Could you share the resourse for training?

### ISSUE THREAD

**Issue by yippp** [Sky24H/image2ink#3]
I am intersting about this repo, and now I want to reproduce it. But some resource are lack for training.
Could you upload the pretrained HED model, i.e., './35.pth'?
I am pleasure if you can share more like some image data for training.
Much thanks to you!

**Comment by sky24h** [comment]
I'm sorry for being impossibly late, I just updated this repo to be compatible with Python 3.9 and free of bugs.
However, I can not provide image data for training due to potential copyright problems.
